export const CONSTANTS = {
  ITR_SERVICE: "Tax Filing",
  ITR_FILING: "Tax Filing",
  GST_FILING: "GST Filing",
  COMPANY_REGISTRATION: "Company Registration",
  TDS_FILING: "TDS Filing",
  TAX_CONSULTATION: "Tax Consultation",
  FEMA_COMPLIANCE_SERVICE: "FEMA Compliance Service",
  ROC_SERVICE: "ROC Filing Service",
  BUSINESS_ADVISORY_SERVICE: "Business Advisory Service",
  TAX_FILING_SERVICE: "Tax Filing Service",

  ADVANCE_TAX_CALCULATION: "Advance Tax Calculation",
  TDS_TCS_RETURN_FILING: "TDS Tcs Return Filing",
  TAX_PLANNING: "Tax Planning",
  OTHERS: "Others",
  REPLY_TO_NOTICE: "Reply To Notice",
  APPEAL: "Appeal",
  BUSINESS_ITR: "Business ITR",
  PROFESSIONAL_ITR: "Professional ITR",
  CAPITAL_GAINS_ITR: "Capital Gains ITR",
  MONTHLY_GST: "Monthly GST",
  QUARTERLY_GST: "Quarterly GST",
  PRIVATE_LIMITED: "Private Limited",
  LLP: "Llp",
  OPC: "Opc",
  PARTNERSHIP: "Partnership",
  NRI_TAX_FILING: "NRI Tax Filing",
  BUSINESS_AUDIT: "Business Audit",

  COMPLEX: "Complex",
  SIMPLE: "Simple",
  PREMIUM: "Premium",

  Others: "Others",
  NRI: "NRI",
  INCOME_BELOW_50L: "Income < 50L",
  INCOME_ABOVE_50L: "Income > 50L",
  FOREIGN_INCOME_AND_ASSETS: "Foreign Income And Assets",
  CAPITAL_GAINS: "Capital Gains",
  BUSINESS_REGULAR: "Business Regular",
  BUSINESS_BASIC: "Business Basic",
  NRI_PREMIUM: "NRI Premium",
  ADVANCE_TAX_BASIC: "Advance Tax (Basic)",
  ADVANCE_TAX_ADVANCED: "Advance Tax (Advanced)",
  TDS_BASIC: "TDS Basic",
  TDS_ADVANCED: "TDS Advanced",
  TAX_PLANNING_BASIC: "Tax Planning Basic",
  TAX_PLANNING_ADVANCED: "Tax Planning Advanced",
  FOREIGN_REMITTANCE: "Foreign Remittance",
  TDS_IMMOVABLE_PROPERTY: "TDS Immovable Property",
  LOWER_TAX_DEDUCTION_CERTIFICATE: "Lower Tax Deduction Certificate",
  TAX_AUDIT: "Tax Audit",
  REPLY_TO_NOTICE_BASIC: "Reply To Notice Basic",
  REPLY_TO_NOTICE_ADVANCED: "Reply To Notice Advanced",
  REPLY_TO_NOTICE_SCRUTINY: "Reply To Notice Scrutiny",
  APPEAL_CIT_A: "Appeal CIT-A",
  APPEAL_ITAT: "Appeal ITAT",

  GST_RETURN_NORMAL: "GST Return (Normal dealer)",
  GSTR_9_9C: "GSTR-9 & 9C Annual Return (Normal dealer)",
  GST_RETURN_COMPOSITE: "GST Return (Composite dealer)",
  GST_ANNUAL_RETURN_COMPOSITE: "GST Annual Return (Composite dealer)",

  YES_NO: "Yes No",
  SINGLE_CHOICE: "Single Choice",
  MULTIPLE_CHOICE: "Multiple Choice",
  GROUP: "Group",

  RESIDENTIAL_STATUS: "Residential Status",
  INCOME_SOURCES: "Income Sources",
  INCOME_SALARY: "Income Salary",
  INCOME_RENTAL: "Income Rental",
  INCOME_BUSINESS: "Income Business",
  INCOME_CAPITAL_GAINS: "Income Capital Gains",
  INCOME_OTHER: "Income Other",
  INCOME_FOREIGN: "Income Foreign",
  TRANSACTION_COUNT: "Transaction Count",
  FOREIGN_INCOME_DETAILS: "Foreign Income Details",

  YES: "Yes",
  NO: "No",
  NOT_AWARE: "Not Aware",
  MORE_THAN_100: "More Than 100",
  FOREIGN_ASSETS_DECLARED: "Foreign Assets Declared",

  BUSINESS: "Business",
  PROFESSION: "Profession",

  SHARES: "Shares",
  MUTUAL_FUNDS: "Mutual Funds",
  IMMOVABLE_PROPERTIES: "Immovable Properties",

  INCOME_TAX: "Income Tax",
  CORPORATE_TAX: "Corporate Tax",
  TDS_TAX: "TDS Tax",
  GST_TAX: "GST Tax",
  INTERNATIONAL_TAX: "International Tax",

  SALARY: "Salary",
  RENTAL: "Rental",
  OTHER: "Other",
  FOREIGN: "Foreign",

  LESS_THAN_100: "Less Than 100",
  SINGLE: "Single",
  MULTIPLE: "Multiple",

  PENDING: "Pending",
  SUBMITTED: "Submitted",
  APPROVED: "Approved",
  REJECTED: "Rejected",

  // documents

  AADHAAR: "Aadhaar",
  PAN_CARD: "PAN Card",
  PASSPORT: "Passport",
  DRIVING_LICENSE: "Driving License",
  VOTER_ID: "Voter ID",
  BANK_STATEMENT: "Bank Statement",
  FORM_16: "Form 16",
  RENT_AGREEMENT: "Rent Agreement",
  PROPERTY_PAPERS: "Property Papers",
  BUSINESS_REGISTRATION: "Business Registration",
  BUSINESS_SETUP: "Business Setup",

  COMPANY_FORMATION: "Company Formation",
  LLP_FORMATION: "LLP Formation",
  STARTUP_INDIA: "Startup India",
  PTRC_PTEC_REGISTRATION: "PTRC/PTEC Registration",
  PARTNERSHIP_FIRM_REGISTRATION: "Partnership Firm Registration",
  MSME_UDYAM_REGISTRATION: "MSME Udyam Registration",
  IMPORT_EXPORT_CODE: "Import Export Code",
  OFFICE_SETUP: "Project / Liasoning / Branch Office Setup",
  GIFT_CITY_STRUCTURING: "GIFT City Structuring",
  PROFESSIONAL_CONSULTATION: "Professional Consultation",

  GST_REGISTRATION: "GST Registration",
  GST_CANCELLATION: "GST Cancellation",
  GST_MODIFICATION: "GST Modification",
  GST_NIL_RETURN: "GST Nil Return",
  QATAR: "Qatar",
  OMAN: "Oman",

 
  GST_LUT: "GST LUT",
  GST_REFUND: "GST Refund",
  GST_APPEAL: "GST Appeal",
  ODI_ANNUAL_FILLING: "ODI Annual Filing",
  FDI_ANNUAL_FILLING: "FDI Annual Filing",
  ODI_FDI_REMITTANCE_FILLING: "ODI/FDI Remittance Filing",
  FEMA_CONSULTING: "FEMA Consulting",
  ANNUAL_FILING_COMPANY: "Annual Filing - Company",
  ANNUAL_FILING_11_LLP: "Annual Filing - LLP (Form 11)",
  ANNUAL_FILING_8_LLP: "Annual Filing - LLP (Form 8)",
  OTHERS_FORMS_FILING_REGULAR: "Other Forms Filing - Regular",
  WINDING_UP: "Winding Up",
  ANY_LEGAL_CONSULTING_FOR_ROC: "Any Legal Consulting for ROC Filing",

  STARTUP_PLAN: "Accounting – Startup Plan",
  BASIC_PLAN: "Accounting – Basic Plan",
  ADVANCE_PLAN: "Accounting – Advance Plan",
  SUPER_PREMIUM_PLAN: "Accounting – Super Premium Plan",
  BUSINESS_GROWTH_PLANNING_AND_STRATEGIES: "Business Growth Planning and Strategies",
  M_AND_A_AND_FUNDRAISING: "M&A and Fundraising",
  VIRTUAL_CFO: "Virtual CFO",
  BUSINESS_CONSULTING_SERVICES: "Business Consulting Services",
  below60: "Below 60",
  above80: "Above 80",
  "60to80": "60 to 80",
};
