export const breadCrumbPath = [
  { label: "Home", href: "/" },
  { label: "Calculators", href: "/calculators" },
  { label: "NPS Calculator", href: "/calculators/nps" },
  { label: "HRA Calculator", href: "/calculators/hra" },
  { label: "NSC Calculator", href: "/calculators/nsc" },
  { label: "SIP Calculator", href: "/calculators/sip" },
  { label: "Old and New Tax Regime", href: "/calculators/old-and-new-tax-regime" },
  { label: "Home Loan EMI Calculator", href: "/calculators/home-loan-emi" },
  { label: "Gratuity Calculator", href: "/calculators/gratuity" },
  { label: "Income Tax Calculator", href: "/calculators/Income-tax" },
  { label: "Blog & Articles", href: "/blogs-articles" },
  { label: "Guides", href: "/guide" },
  { label: "User Support", href: "/user-support" },
  { label: "Blog Details", href: "/blog/:blogId" },
  { label: "Product Details", href: "/product/:productId" },
  { label: "User Profile", href: "/user/:userId" },
  { label: "Income Tax Return", href: "/income-tax-return-file" },
];