import React, { useEffect } from "react";

const TermsAndConditions = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="p-10">
      <h3 className="text-center font-semibold text-2xl">
        EZYFILING GENERAL T&C / USER AGREEMENT{" "}
      </h3>
      <p className="mt-8 text-justify">
        These Terms and Conditions of Use (“Terms”) govern your access to and
        use of the Platform (as defined below) and the Services (as defined
        below) provided by us, our Strategic Partners, and third-party service
        providers. By accessing or using the Platform and Services, you
        acknowledge that you have read, understood, and agree to be bound by
        these Terms. These Terms outline the rights, obligations, and
        expectations between you and us, including but not limited to the
        conditions of access, permitted use, and limitations of liability.{" "}
      </p>
      <p className="mt-4 text-justify">
        Specifically, these Terms cover the following aspects:
      </p>
      <ul className="list-[lower-latin] list-inside text-justify">
        <li>our policy regarding the changes and updates to these Terms</li>
        <li>
          Description of the Platform and Services offered by us, our Strategic
          Partners, and third-party service providers
        </li>
        <li>sign-up process and information required by us; 
        </li>
        <li>conditions regarding use of the Platform and the Services; 
        </li>
        <li>
        terms of use and conditions regarding the information made available by us on the Platform; 

        </li>
        <li>
        intellectual property rights and ownership of the content on our Platforms and the conditions of use of such content
        </li>
        <li>Know Your Client ("<strong>KYC</strong>") requirements</li>
        <li>our policy regarding the communications and notifications sent by the Platform</li>
        <li>
        disclaimers, limitation of liability and indemnification obligations in relation to the Services provided; and
        </li>
        <li>
          legal rights and Obligations in case of  violation of these Terms by you.
        </li>
      </ul>
      <p className="mt-5 text-justify">
        These Terms apply to and govern the use of or access to the website
        www.ezyfiling.com, and on its mobile/web applications (hereinafter,
        collectively referred to as the “<strong>Platform</strong>”), by the user (hereinafter,
        “<strong>you</strong>”, “<strong>your</strong>”, or “<strong>User</strong>”). The Terms shall apply to the User in relation
        to the relevant Services availed on the Platform.{" "}
      </p>
      <p className="mt-5 text-justify">
        The Platform is provided by <strong>APT Global Fincon Private
        Limited </strong>(hereinafter, “<strong>Company</strong>” “<strong>ezyfiling</strong>” or “<strong>our</strong>” or “<strong>we</strong>” or “<strong>us</strong>”), a
        company incorporated under the Companies Act 2013, having its corporate
        office at <strong>Flat 301, Kamla Hub, N S Road No. 1, Near Criti Care Hospital, Next
        to Aromas Café, JVPD Scheme, Juhu, Vile Parle West, Mumbai – 400049,
        INDIA.</strong>
      </p>
      <p className="mt-4 text-justify">
       <strong> User and Company are each a “Party” and collectively the “Parties”.</strong>
      </p>
      <div className="mt-4 text-justify">
      These Terms are an electronic record in terms of the (Indian) Information Technology Act, 2000 and rules thereunder as applicable and as amended from time to time (“<strong>IT Act</strong>”). This electronic record is generated by a computer system and does not require any physical or digital signatures. These Terms are published in accordance with the provisions of Rule 3(1)(a) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 framed under the IT Act (as amended from time to time), that require publishing the terms of services and practices for access or usage of Platform and Services. These Terms constitute a binding and legally enforceable contract between the Company and User (as defined below). By registering on or using the Platform or availing the Services, you agree to be bound by the Terms. If you are using the Platform on behalf of an organization, you are agreeing to the Terms on behalf of that organization. (In which “<strong>you</strong>”, “<strong>your</strong>” or “<strong>user</strong>” will refer to that organisation)   ‍{" "}
        <br />
        You represent that you are at least 18 (eighteen) years of age and have not been previously suspended or removed by the Company, or disqualified for any other reason, from availing the Services or using the Platform. In addition, you represent and warrant that you have the right, authority and capacity to agree to the Terms and to abide by them. You shall not impersonate any person or entity, or falsely state or otherwise misrepresent your identity, age or affiliation with any person or entity. In the event of any violation of the Terms, the Company reserves the right to suspend or permanently prevent you from availing the Services or  
        <br />
        If you do not agree to be bound by these terms, you must not use the Platform. By continuing to use the Platform or the Services you expressly agree and undertake to be bound by these terms. Subject to applicable laws, these Terms (and any changes thereto) will become applicable to you retrospectively on and from the date of your first use of the Platform. 
      </div>
      <h3 className="font-semibold text-xl">Definition(s): </h3>
      <p className="mt-5 text-justify">
      The following terms shall have the meanings hereinafter assigned to them. Any terms not specifically defined below shall have the same meaning as assigned to them in the respective clauses/sub-clauses/paragraphs of these Terms and Conditions. 
      </p>
      <ul className="list-[lower-latin] list-inside text-justify ">
        <li>
          <strong>"ezyfiling"</strong> is a brand operated by <strong>APT Global Fincon
          Private Limited</strong>, a company engaged in providing tax compliance, GST
          filing, and other financial services. ezyfiling functions as a
          platform connecting businesses, individuals, and service providers,
          facilitating tax-related solutions and ensuring regulatory compliance.
          Throughout this Agreement, references to "ezyfiling" shall include its
          affiliates, subsidiaries, employees, and authorized representatives.
        </li>
        <li>
        "<strong>User</strong>" refers to any individual, entity, or organization that accesses, registers, or uses the services provided by APT Global Fincon Private Limited under its brand “ezyfiling” (the “Platform”), whether as a customer, subscriber, visitor, or any other capacity. The term includes but is not limited to individuals filing taxes, businesses utilizing compliance services, and any authorized representatives acting on their behalf. 
        </li>
        <li>
        "<strong>Data</strong>" refers to any information, including personal, financial, or transactional data, that users submit, store, or share on the ezyfiling platform. Users grant APT Global Fincon Private Limited the right to process, store, and use such data for providing and improving services, facilitating third-party integrations, and other operational purposes as per the Privacy Policy. Users acknowledge the risk of data loss, for which the Company shall not be liable.  
        </li>
        <li>
        "<strong>Information</strong>" refers to any data, updates, or guidance provided on the <strong>ezyfiling</strong> platform, including compliance deadlines, tax-related news, and regulatory updates 
        </li>
        <li>
        “<strong>Platform</strong>” refers to the website, mobile application, and any other digital interfaces owned or operated by the Company. 
        </li>
        <li>
          <strong>"GST"</strong> shall mean goods and services tax.
        </li>
        <li>
        “<strong>Intellectual Property Rights</strong>” shall mean either individually or collectively the following worldwide rights relating to intangible property:
        <ol className="list-[lower-roman] list-inside pl-5 text-justify">
         <li> patents, patent disclosures, and patent applications; </li>
         <li> copyrights, trademarks, service marks, and trade dress; </li>
         <li> trade secrets and proprietary rights in business methodologies;</li>
         <li> domain names and website-related rights; and </li>
         <li> any other intellectual or proprietary rights under Applicable Law. </li>
         </ol>
        </li>
        <li>
        “<strong>Services</strong>” means all online tax filing, GST compliance, accounting, and other financial services provided by the Company. 
        </li>
        <li>
          <strong>"KYC"</strong> refers to Know Your Customer norms, including
          identity verification and documentation requirements as per applicable
          laws.
        </li>
        <li>
          <strong>"Applicable Laws"</strong> means all laws, rules, regulations,
          guidelines, and policies issued by regulatory authorities governing
          tax filing, GST compliance, and digital transactions.
        </li>
        <li>
          <strong>"Payment Gateway"</strong> refers to third-party payment
          processors used for facilitating online payments.
        </li>
        <li>
          <strong>"Confidential Information"</strong> includes any non-public
          data, financial details, business information, or personal information
          shared by the User or Company.
        </li>
      </ul>
      <h3 className="font-semibold text-xl mt-4">1. Changes to these Terms</h3>
      <p className="pl-5  mt-5 text-justify">
     1.1. Please note that these Terms may change from time to time. We reserve the right to modify or amend these Terms. While we will make reasonable efforts to keep you posted on any updates to these Terms, to make sure that you are aware of any changes, we encourage you to periodically review them whenever accessing or using the Platform to be continuously aware of the changes that we may be carrying out to these terms.  
      </p>
      <p className="pl-5 mt-5 text-justify">
        1.2. In the event we modify these Terms, by continuing to access and use the Platform, you will have confirmed your acceptance to any such modifications. Your continued use will be adequate proof that you have expressly agreed to the terms of these Terms which shall apply from the date of your first use of the Platform. In addition, when using the Platform, you will be subject to any posted guidelines, supplementary terms, policies, or disclaimers made available or issued by us from time to time, including but not limited to the Privacy Policy available at our website. All such supplementary terms, policies, guidelines or disclaimers are hereby incorporated by reference into these Terms.  
      </p>
      <p className="pl-5 mt-5 text-justify">
        1.3. If you have any comments or questions regarding the Terms, or wish to report any violation of the Terms, you may contact us at our contact details mentioned in our website. 
      </p>

      <h3 className="font-semibold text-xl mt-4">
        2. About the Platform and the Services
      </h3>
      <p className="pl-5 mt-5 text-justify">
        2.1. The Platform primarily functions as a technology service provider,
        offering various software solutions and access to services related to
        regulatory and business compliances. These services include, but are not
        limited to:{" "}
      </p>
      <ol className="list-none pl-10 text-justify">
        <li>
          (i) Goods and Services Tax (“GST”) compliance solutions, including GST filing
        </li>
        <li>
          (ii) Income Tax Return (“ITR”) filing
        </li>
        <li>
          (iii) Foreign Exchange Management Act (“FEMA”) compliance
        </li>
        <li>
          (iv) Registrar of Companies (“ROC”) filing
        </li>
        <li>
          (v) Business setup assistance
        </li>
        <li>
          (vi) Business consultancy services
        </li>
      </ol>


      <p className="pl-5  mt-5 text-justify">
        2.2. The Platform also enables you to access and avail these Services directly from the Company, its Strategic Partners, and third-party service providers associated with the Company from time to time. Additionally, the Platform facilitates communication with such Strategic Partners and third parties for seamless access to the Services. 

      </p>
      <p className="pl-5 mt-5 text-justify">
        2.3. The services rendered by the Company and other Strategic Partners
        and third-party service providers of the Company are collectively
        referred to as “<strong>Services</strong>”.
      </p>

      <h3 className="font-semibold text-xl mt-4">
        3. Sign-Up and Consent Requirements
      </h3>
      <p className="pl-5 mt-5 text-justify">
        3.1 To avail the Services, you may have to provide us with necessary details including but not limited to your name, mother’s name, father’s name, date of birth, gender, Permanent Account Number (“PAN”), signature, marital status, nominee details, cancelled cheque, photograph and video recording, email id, phone number, educational or professional qualification, business name, business address, nature of business, Goods and Service Tax Identification Number (“GSTN”), Tax Deduction and Collection Account Number (“TAN”), bank account details, Unified Payment Interface (“UPI”) ID, and/or other payment related details etc., as applicable.  
      </p>
      <p className="pl-5  mt-5 text-justify">
        3.2 You agree to provide the above stated information, or such other information as may be necessary or required by us to provide the Services, at the time of sign-up or at any subsequent stage. Further, you acknowledge that the act of providing your Aadhaar ID is voluntary in nature unless mandated under applicable law. You may choose to provide us with an alternative KYC proof. 
      </p>
      <p className="pl-5 mt-5 text-justify">
        3.3  You warrant to provide true, accurate, current and complete information about yourself and you agree to not misrepresent your identity or your account information. You agree to keep your account information up to date and accurate.
      </p>
      <p className="pl-5 mt-5 text-justify">
        3.4  If you upload information relating to any third parties, you should ensure that any such information is uploaded only after obtaining express written consent from them for using their information on the Platform. Further, you should ensure that express written consent from such persons is obtained to receive communications from the Company regarding: information about us and the Services; promotional offers and services from us and our third-party service providers and Strategic Partners, and any other matter in relation to the Services. If such third parties fail to provide written consent, or withdraw consent, you shall immediately cease to use the Services in relation to them. You will be solely responsible for obtaining such consent from third parties and we assume that such consent is sought and received by you if you provide such information relating to any of such third parties any time during the use of the Platform.  
      </p>
      <p className="pl-5  mt-5 text-justify">
        3.5  If you provide any information that is false, inaccurate or outdated, or we have reasonable grounds to suspect that such information is false, inaccurate or outdated, we will be entitled to suspend or terminate your account and prohibit any and all current or future use of the Platform by you. You are responsible for maintaining the confidentiality of the account and are fully responsible for all activities that occur under your account.  
      </p>
      <p className="pl-5 mt-5 text-justify">
        3.6 You agree to immediately notify us in writing in of any disclosure or unauthorized use of your profile or any other breach of security with respect to your profile. 
      </p>
      <h3 className="font-semibold text-xl mt-4">
        4. Use of and Access to the Platform
      </h3>
      <p className="pl-5 mt-5 text-justify">
        4.1 You agree to use the Platform only for lawful purposes, and that you are responsible, liable and accountable for all activities that take place through your use of Platform or availing the Services. We exclude any liability arising out of use of the Platform.  
      </p>
      <p className="pl-5 mt-5 text-justify">
        4.2 You understand, accept and agree that the payment facility provided by us is neither a banking nor financial service, but we merely act as a facilitator providing an electronic payment option, automated online electronic payment option, for the transactions on the Platform using the existing authorized banking infrastructure and the payment gateway/payment aggregator networks. Further, by providing payment facility, we are neither acting as trustees nor acting in a fiduciary capacity with respect to the transaction.
      </p>
      <p className="pl-5 mt-5 text-justify">
        4.3 Service Level Terms: We will use commercially reasonable efforts to provide you the Platform. We will provide you with reasonable technical support services in accordance with our standard practices. We do not make any commitment that the Platform will be available at all times or during any down time
        <ol  className="list-[lower-roman] list-inside pl-10 text-justify">
           <li>caused by outages to any public Internet backbones, networks or servers,</li>
             <li>caused by any failures of your equipment, systems or local access services,</li> 
              <li> for previously scheduled maintenance,</li>
               <li> caused by any third party vendor or service provider of the Company,</li> 
               <li> caused by any failure of systems or servers of any third party including that of the government and its authorities and/or financial institutions such as asset management companies or any financial intermediaries,</li>
                <li> attributable to events such as strikes, riots, insurrection, fires, floods, explosions, war, governmental action, labor conditions, earthquakes, natural disasters, hacking, phishing or interruptions in Internet services to an area where the Company or its servers are located or co-located, or </li> 
                <li> required pursuant to instructions received by us from any governmental or regulatory authority. </li>
        </ol>
      </p>
     
      <p className="pl-5 mt-5 text-justify">
        4.4 Updates: From time to time, we may provide upgrades, patches, enhancements, or fixes for the Platform to you generally without additional charge and such updates will become part of the Platform and subject to the Terms. Notwithstanding the foregoing, we shall have no obligation under these Terms or otherwise to provide any such updates. You understand that the Company may cease supporting old versions or releases of the Platform at any time in its sole discretion. 
      </p>
      <p className="pl-5 mt-5 text-justify">
        4.5 By accessing or using the Platform or by availing Services, you
        agree not to:
      </p>

      <ol className="list-[lower-roman] list-inside pl-10 text-justify">
        
        <li>
          host, display, upload, modify, publish, transmit, update or share any information (if provided with the functionality to do so on the Platforms) that:
        </li>

        <li> belongs to another person and to which the user does not have any right</li>
        <li>is defamatory, obscene, pornographic, paedophilic, invasive of another’s privacy, including bodily privacy, insulting or harassing on the basis of gender, libellous, racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws of India </li>
        <li> is harmful to minors</li>
        <li> infringes any patent, trademark, copyright or other proprietary rights </li>
        <li> violates any law for the time being in force</li>
        <li> deceives or misleads the addressee about the origin of the message or knowingly and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact</li>
        <li> impersonates another person </li>
        <li> threatens the unity, integrity, defence, security or Sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any foreign states</li>
        <li> contains software virus or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource</li>
        <li>is patently false and untrue, and is written or published in any form, with the intent to   mislead or harass a person, entity or agency for financial gain or to cause any injury to any person.  </li> 
        
        <li>
          violate the Terms or any law for the time being in force;
        </li>
        <li>
          conduct or forward surveys, contests, pyramid schemes or chain
          letters involving the Services;
        </li>
        <li>
          impersonate any person or entity, falsely claim or otherwise
          misrepresent your affiliation with any person or entity, or access the
          accounts of others without permission, forge another person’s digital
          signature, misrepresent the source, identity, or content of
          information transmitted via the Services, perform any other similar
          fraudulent activity;
        </li>
        <li>
          infringe our or any third party’s patent, trademark, copyright
          or other intellectual property rights, proprietary rights, rights of
          publicity or privacy;
        </li>
        <li>
          use the Services if you are under the age of 18 (eighteen)
          years;
        </li>
        <li>
          post or transmit any message (if provided with the functionality
          to do so on the Platforms) which discloses private or personal matters
          concerning any person or, is grossly harmful, harassing, hateful
          and/or disparaging;
        </li>
        <li>
          post or transmit (if provided with the functionality to do so on
          the Platforms) any message, data, image or program which is
          blasphemous, vulgar, or offensive in nature;
        </li>
        <li>
          refuse to cooperate in an investigation or provide confirmation
          of your identity or any other information provide by you to us;
        </li>
        <li>
          remove, circumvent, disable, damage or otherwise interfere with
          security-related features of the Platform and Services or features
          that enforce limitations on the use of the Services or the Platform;
        </li>
        <li>
          reverse engineer, decompile, disassemble or otherwise attempt
          to discover the source code of as regards Services or Platform or any
          part thereof, except and only to the extent this is expressly
          permissible by applicable law;
        </li>
        <li>
          use the Services or the Platform in any manner that could
          damage, disable, overburden, or impair it, including, without
          limitation;
        </li>
        <li>
          using the Services or the Platform in an automated manner;
        </li>
        <li>
          modify, adapt, translate or create derivative works based upon
          the Services and Platform or any part thereof, except and only to the
          extent that this is permissible by applicable law;
        </li>
        <li>
          intentionally interfere with or damage operation of the
          Services or the Platform or any other user’s enjoyment of it, by any
          means, including uploading or otherwise disseminating viruses, adware,
          spyware, worms, or other malicious code or file/ program with
          contaminating or destructive features or which are designed to
          interrupt, destroy or limit the functionality of any computer
          resource;
        </li>
        <li>
          use any robot, spider, other automatic device, or manual
          process to monitor or copy the Platform without prior written
          permission;
        </li>
        <li>
          take any action that imposes an unreasonably or
          disproportionately large load on our infrastructure/network;
        </li>
        <li>
          use the facilities and capabilities of the Platform to conduct
          any activity or solicit the performance of any illegal activity or
          other activity which infringes the rights of others;
        </li>
        <li>
          use the Platform to collect or obtain personal information,
          including without limitation, financial information, about other users
          of the Platform, except and only as expressly provided in the Terms;
        </li>
        <li>
          use the Services in a manner that results in or may result in
          complaints, disputes, reversals, chargebacks, fees, fines, penalties
          and other liability to us, a third party or you.
        </li>

      </ol>

      <h3 className="font-semibold text-xl mt-4">5. Information</h3>
      <p className="pl-5 mt-5">
        5.1. While we use commercially reasonable efforts to facilitate provisions of the information, information on compliance deadlines for filing various tax returns and other statutory forms, etc on the Platform, we are not responsible for any errors or omissions, or for the results obtained from the use of or reliance on this information. Specifically, certain links in Platform may connect to other websites maintained by third parties over which we have no control. If you access such links, your use of the third-party websites will be governed by the policies of such websites. We encourage you to review the terms and policies of such websites.  
      </p>
      <p className="pl-5 mt-5">
        5.2. Any information, information on compliance deadlines for filing various tax returns and other statutory forms; relevant tax related news; and any other regulatory news made available through the Platform is for general guidance on matters of interest only. In particular, impact of laws and regulations can vary widely based on the specific facts involved. Given the changing nature of laws, rules and regulations, and the inherent hazards of electronic communication, there may be delays, omissions or inaccuracies in such information. Accordingly, the information provided through or in relation to this Platform is so done with the understanding that we are not herein engaged in rendering legal, accounting, tax, or other professional advice and services. As such, it should not be used as a substitute for consultation with professional accounting, tax, legal or other competent advisers. Before making any decision or taking any action, you should consult a professional advisor. You acknowledge that the provision of the Platform or Services does not constitute the provision of any specific advice nor any other professional services or advice of any kind (including any tax services). Any use of the Platform or Services (including reliance on any of the contents therein) is at your sole risk.  
      </p>
      <p className="pl-5 mt-5 text-justify">
        5.3. While we use reasonable efforts to facilitate the information made
        available through the Platform is being obtained from reliable sources,
        we are not responsible for any errors or omissions, or for the results
        obtained from the use of or reliance on this information.
      </p>
      <p className="pl-5 mt-5 text-justify">
        5.4. We do not make any representations as to the accuracy or any other
        aspect of information contained in other websites. All information made
        available through the Platform is provided "AS IS", with no guarantee,
        representation, or commitment of completeness, accuracy, timeliness or
        of the results obtained from the use of this information, and without
        warranty of any kind, express or implied, including, but not limited to
        warranties of performance, merchantability and fitness for a particular
        purpose.
      </p>

      <h3 className="font-semibold text-xl mt-4">
        6. Intellectual Property Rights and Ownership
      </h3>
      <p className="pl-5 mt-5 text-justify">
        6.1 We own the rights in the design, compilation, and look and feel of
        our Platform. It also includes rights in all copyrighted works,
        trademarks, designs, inventions, and other intellectual property.
        Subject to compliance with these Terms, we grant you a non-exclusive,
        non-transferable, non-sub licensable, royalty-free, revocable, and
        limited access to use the Platform and the Services in accordance with
        these Terms.
      </p>
      <p className="pl-5 mt-5 text-justify">
        6.2 You agree not to copy, distribute, modify or make derivative works
        of any of our content or use any of our intellectual property rights in
        any way not expressly permitted by us.
      </p>
      <p className="pl-5 mt-5 text-justify">
        6.3 We may provide you with summary of the news or information that is
        already available in the public domain. Further we may provide you an
        electronic link to the original source of such news or information. Upon
        clicking the electronic link, you may be directed to the website of a
        third party who has published that news or information. We do not own
        any intellectual property rights in the information published by such
        third party.
      </p>
      <p className="pl-5 mt-5 text-justify">
        6.4 Use of data: Notwithstanding anything to the contrary contained
        herein, when you enter or upload your data onto the Platform, you
        expressly agree, covenant, consent and grant us, our Strategic Partners,
        our third party service providers and our group companies, affiliates,
        all rights, licences and consents to host, use, copy, transmit, process,
        store, share, analyse, display, make derivations, and back up all data
        you submit to us through our services and as required by us including
        but not limited to personal data and any other data relating to
        financial information of yourself and others, and further to:
      </p>
      <ul className="list-[lower-roman] list-inside pl-10 text-justify">
        <li>
          Enable you to use the Platform and avail the Services including the
          services provided by our partners, third parties, and affiliates;
        </li>
        <li>Allow us to improve, develop and protect our Services;</li>
        <li>
          Create, market or provide new services through the Company or its
          Strategic Partners, group companies, and affiliates;
        </li>
        <li>Communicate with you about our Platform and the Services; and</li>
        <li>send you information we think may be of interest to you. You agree, represent and warrant that you have and you will maintain, all rights to allow the Company, our Strategic Partners and/ or any third party service providers, and our affiliates, to host, use, compile, copy, transmit, process, store, share, analyse, display, make derivations, and back up all your data and retain aggregated customer data, including without limitation in combination with data of other users. The terms of use and sharing of such data are set out in our Privacy Policy.  </li>
      </ul>
      <p className="pl-5 mt-5">
        6.5 Data loss: Data loss is an unavoidable risk when using any
        technology. You are responsible for maintaining copies of your data
        entered into the Platform or for availing the Services.
      </p>
      <p className="pl-5 mt-5">
        6.6 No compensation: Whatever the cause of any downtime, access issues
        or data loss, your only recourse is to discontinue using the Platform or
        the Services.
      </p>
      <h3 className="font-semibold text-xl mt-4">
        7.  Know your Customer/ Client Requirements
      </h3>
      <p className="pl-5 mt-5">
        7.1. You agree and provide your express consent to provide certain information and documents that may be necessary to ascertain your eligibility to use the Platform or avail the Services including but not limited to your KYC Documents to us, to entities for whom we act as a technology facilitator and Platform provider including but not limited to Right Horizons , to online payment gateways, operators and aggregators, and, or to our affiliates to use, copy, transmit, process, store, share, analyse, make derivations, and back-up such KYC Documents and information. For the purpose of these Terms, ‘KYC Documents’ shall mean to include mobile number, mother’s name, father’s name, email address, password, date of birth, gender, PAN, signature, marital status, nominee details, cancelled cheque, photograph and video recording, etc. and other information which may be sought either during Sign-up or at any stage later. You agree and warrant to provide valid, true, complete, and up-to-date KYC Documents. You acknowledge and agree that any incorrect or misleading information provided shall constitute a material breach of these Terms. 
      </p>
      <p className="pl-5 mt-5">
        7.2. We may use your personal data and in order to provide Services to you. Your personal information and KYC documents may be processed by or transferred or disclosed to and/or by third parties like AMC’s, RTA’s (Registrar and Transfer agents), KYC Registration Agency (“KRA”), payment gateways, statutory bodies or agencies, or third-party service providers & Strategic Partners etc. 
      </p>
      <h3 className="font-semibold text-xl mt-4">8. Communication Policy</h3>

      <p className="pl-5 mt-5">
        8.1  You agree to receive communications from the Company regarding: 
        <ol className="list-[lower-roman] list-inside  text-justify">
        <li>information relating to use of the Platform or Services; </li>
        <li> information about the Company and the Services; </li>
        <li> promotional offers and services from the Company and its Strategic Partners and third-party partners, and </li>
        <li> any other matter in relation to the Services. In case you access the Platform on behalf of a third party (after obtaining their prior consent), you acknowledge and agree that we are permitted to send any or all of the above communications to your customers or other third parties whose information you have made available on the Platform. </li>
        </ol>
      </p>
      <p className="pl-5 mt-5">
        8.2 We may send alerts to the mobile phone numbers provided by you, either of yourself or your customers or any third parties, via e-mail, SMS, WhatsApp messages or push notifications or any other means. If your mobile number is registered in the Do Not Disturb (“DND”) list of Telecom Regulatory Authority of India, you may not receive SMS from us. In such case, you will be responsible for taking all steps to deregister from the DND list and will not hold us liable for non-receipt of SMS.
      </p>
      <p className="pl- mt-5">
        8.3 We shall not be under any obligation to confirm the authenticity of the person(s) receiving the alert. You cannot hold the Company liable for non-availability of the SMS/email alert/push notifications service in any manner whatsoever.  
      </p>
      <p className="pl-5 mt-5">
        8.4 The SMS/e-mail alert/push notification service provided by us is an additional facility provided for your convenience and that it may be susceptible to error, omission and/or inaccuracy. You shall not hold the Company liable for any loss, damages, claim, expense including legal cost that may be incurred/suffered by you on account of the SMS/e-mail alert/push notification facility.
      </p>
      <p className="pl-5 mt-5">
        8.5 The clarity, readability, accuracy and promptness of providing the SMS/e-mail alert/push notification service depend on many factors including the infrastructure and connectivity of the network service provider. We shall not be responsible for any non-delivery, delayed delivery or distortion of the alert in any way whatsoever
      </p>
      <p className="pl-5 mt-5">
        8.6 You understand that the Company cannot and does not guarantee or warrant that files available for download through the Platform will be free of viruses, worms or other code that may be damaging. You are responsible for implementing procedures to satisfy your particular requirements of internet security and for accuracy of data input and output. 

      </p>

      <h3 className="font-semibold text-xl mt-4">
        9.  Third party Services on the Platform
      </h3>
      <p className="pl-5 text-justify mt-5">
        9.1. Our Platform includes products and services made available by third party service providers. These third-party service providers may have additional terms that apply to you. You agree to be bound by such other additional terms. Third-party products and services are subject to terms and conditions and privacy policies set by their providers. These include how the provider will use your data that you make available to them. The descriptions of third-party products and services that we publish, and any associated links, have been provided to us by the providers. The providers are solely responsible for any representations contained in those descriptions. We don’t endorse or assume any responsibility for third-party products or services. 

      </p>

      <p className="pl-5 text-justify mt-5">
        9.2. We make no representations and hereby expressly exclude all warranties and liabilities arising out of or pertaining to such third-party services, including their accuracy or completeness. Further, all intellectual property rights in and to third party services are the property of the respective third parties.
      </p>

      <p className="pl-5 text-justify mt-5">
        9.3 We not take any responsibility for or guarantee for any transaction or communication initiated or executed by the user, directly or indirectly, with any third-party consultant or service provider of ezyfiling.com without approval or routed via ezyfiling.com {" "}
      </p>

      <h3 className="font-semibold text-xl mt-4">
        10. Termination of Access to the Platform
      </h3>

      <p className="pl-5 mt-5">
      We may terminate or suspend your access to Platform or access to all or any of data:
      </p>
      <ol className="list-[lower-roman] list-inside pl-5 text-justify">
      <li>at our discretion;</li> 
       <li>if you fail to comply with these Terms or the Privacy Policy;</li>
        <li>in case of inactivity for long periods; or </li>
        <li> in case of any fraud, insolvency or bankruptcy in relation to you.</li>
      </ol>
      <p className="pl-5 mt-5">You agree that our right to terminate does not depend on whether you breach these Terms or not.</p>
    
      <h3 className="font-semibold text-xl mt-4">
        11. Warranties and Disclaimers
      </h3>
      <p className="pl-5 text-justify mt-5">
        11.1. We are a technology service provider that facilitates the use of
        compliance-related services. However, we do not assume liability for the
        accuracy, completion, or legal validity of any filings, transactions, or
        services availed through the Platform. We shall not be responsible for
        any claims, damages, or losses suffered by you or any third party,
        directly or indirectly, arising from{" "}
        <ul className="list-[lower-roman] pl-10">
          <li>The use or misuse of the Platform.</li>
          <li>
            Errors, delays, or failures in payment processing via third-party
            gateways.
          </li>
          <li>
          Any disputes between users and third parties related to services availed through the Platform. You acknowledge that payments made using links generated on the Platform are processed by third-party payment service providers, and we shall not be liable for any failed transactions, unauthorized access, or financial losses incurred in this regard.  
          </li>
        </ul>
      </p>

      <p className="pl-5 text-justify mt-5">
        11.2. You acknowledge that your use of the Platform and Services is at your sole risk. The Platform and Services are provided on an "as is" and "as available" basis, without any warranties, except as expressly stated in these Terms. To the maximum extent permitted by law, the Company, its Strategic Partners, and third-party service providers disclaim all implied warranties, including but not limited to: 
        <ul className="list-[lower-roman] pl-10 text-justify">
          <li>
            Fitness for a particular purpose – We do not guarantee that the
            Platform will meet your specific needs beyond the scope of the
            services offered;
          </li>
          <li>
            Uninterrupted or error-free service – While we strive to provide
            seamless service, we do not warrant that the Platform will always
            function without delays, interruptions, or errors;
          </li>
          <li>
            Accuracy of information – Any tax, compliance, or financial
            information provided through the Platform is for general guidance
            and should not be considered professional advice. Users are
            encouraged to consult qualified professionals when needed;
          </li>
          <li>
            Corrections of errors – We continuously work to improve our
            Platform, but we do not guarantee that all errors, bugs, or
            technical issues will be corrected immediately.
          </li>
        </ul>
      </p>
      <p className="pl-5 mt-5">
        11.3. You acknowledge and agree that certain Services provided on the Platform are further dependent on the functioning of the technology infrastructure of various third parties including that of the government agencies and, or statutory authorities. You agree that the Company shall not be liable or responsible for any discrepancy in the Services owing to delay or failure of any activity by any such third parties including but not limited to delay or failure by government agencies and, or statutory authorities such as Goods and Services Tax Network, National Informatics Centre. The delay or failure may be as a result of, network or connectivity failure, device or application failure, GST’s System’s failure, possible down time at GST System’s end or any other technical or non-technical error of any nature, whether foreseen or unforeseen. 

      </p>
      <h3 className="font-semibold text-xl mt-4"> 12. Exclusion of Damages</h3>
      <p className="pl-5 text-justify mt-5">
        We shall not be liable for any damages, losses, or claims arising out of
        or in connection with the use or inability to use the Platform and
        Services, including but not limited to:
        <ul className="list-[lower-roman] pl-10 text-justify">
          <li>
            Errors or inaccuracies in the information provided on the Platform;
          </li>
          <li>
            Technical issues, bugs, or interruptions affecting the Platform or
            Services;
          </li>
          <li>
            Unauthorized access, security breaches, or data leaks resulting from
            factors beyond our control;
          </li>
          <li>
            Statements, actions, or conduct of third parties using or
            interacting with the Platform;
          </li>
          <li>
            Disputes between users or between users and third parties related to
            transactions, filings, or services facilitated through the Platform;
          </li>
          <li>
            Any other issues arising from third-party services (including
            government portals, payment gateways, or external compliance service
            providers).
          </li>
        </ul>
      </p>
      <h3 className="font-semibold text-xl mt-4">13. Indemnification</h3>
      <p className="pl-5 text-justify mt-5">
        13.1. You agree to defend, indemnify, and hold harmless the Company,
        including its affiliates, officers, directors, employees, and
        representatives, from and against any claims, liabilities, losses,
        damages, costs, or expenses (including reasonable attorneys’ fees and
        court costs) arising from or related to: 
        
        <ul className="list-[lower-roman] pl-5 text-justify">
          <li> Breach or non-compliance
        with these Terms, including failure to meet obligations, consents,
        representations, or warranties.</li> 

        <li>Misrepresentation, negligence,
        fraud, willful concealment, or misconduct in using the Platform or
        Services. </li>

        <li> Use of the Platform for unlawful, fraudulent, or
        unauthorized activities.</li>

         <li> Any harm, damage, or injury (including
        reputational damage) to third parties resulting from your actions or
        omissions. </li>

        <li>Any claims by third parties due to your use of the
        Platform or Services.</li> 

         <li>Any violation of applicable laws,
        regulations, or compliance requirements.
        </li> 

        </ul>
      </p>
      <p className="pl-5 mt-5">
        13.2. You acknowledge that any violation of these Terms may cause irreparable harm to the Company and its Strategic Partners. In such cases, monetary damages may be inadequate, and the Company reserves the right to seek injunctive or equitable relief without requiring proof of financial loss. If the Company initiates legal action against you for a violation of these Terms, you agree to bear all reasonable legal costs and attorney fees incurred by the Company, in addition to any other relief granted by law. {" "}
      </p>

      <h3 className="font-semibold text-xl mt-4">14. Miscellaneous</h3>
      <p className="pl-5 text-justify mt-5">
        14.1 <span className="font-semibold">Notice:</span> All notices,
        requests, demands, approvals, requests for approvals or other
        communications under the Terms shall be in writing. Notice will be
        sufficiently given for all purposes as follows: 
        <ul className="list-[lower-roman] pl-5 text-justify">
        <li> upon delivery when
        personally delivered to the recipient,</li>

         <li> upon receipt when mailed by
        certified mail, 
        </li>

        <li>upon delivery when delivered by recognized
        international overnight courier,</li> 

         <li> upon receipt when sent by fax
        with confirmation.
        </li>
        </ul>
      </p>
      <p className="pl-5 text-justify mt-5">
        14.2 <span className="font-semibold">Merger/Modification:</span> 
        Each Party acknowledges that it has read the Terms, it understands it, and agrees to be bound by its terms, and further agrees that this is the complete and exclusive statement of the Terms between the Parties, which supersedes and merges all prior proposals, understandings and all other agreements, oral and written, between the Parties relating to the Terms.  
      </p>
      <p className="pl-5 text-justify mt-5">
        14.3{" "}
        <span className="font-semibold">Governing Law and Jurisdiction:</span>{" "}
        These Terms shall be governed by and construed and enforced in accordance with the laws of India. Any controversies, conflicts, disputes, or differences arising out of these Terms shall be resolved by arbitration in Mumbai in accordance with the Arbitration and Conciliation Act, 1996 for the time being in force, which is deemed to be incorporated by reference in this Clause. The tribunal shall consist of 1 (one) arbitrator appointed by us. The language of the arbitration shall be English. The parties to the arbitration shall keep the arbitration confidential and not disclose to any person, other than on a need to basis or to legal advisors, unless required to do so by law. The decision of the arbitrator shall be final and binding on all the Parties hereto. Subject to other provisions in this Clause, courts in Mumbai shall have exclusive jurisdiction over all issues arising out of these Terms or the use of the Services.  
      </p>
      <p className="pl-5 text-justify mt-5">
        14.4 <span className="font-semibold">Severability:</span> 
        If any provision of the Terms is invalid under any applicable statute or rule of law, it is to that extent to be deemed omitted and all other terms and provisions of the Terms shall nevertheless remain in full force and effect so long as the economic or legal substance of the transactions contemplated hereby is not affected in any manner materially adverse to any Party. Upon such determination that any term or other provision is invalid, illegal or incapable of being enforced, the Parties shall negotiate in good faith to modify the Terms so as to effectuate the original intent of the Parties as closely as possible in an acceptable manner in order that the transactions contemplated hereby are consummated as originally contemplated to the greatest extent possible.  
      </p>
      <p className="pl-5 text-justify mt-5">
        14.5 <span className="font-semibold">Waiver:</span> 
        A waiver by either Party of any terms or conditions of the Terms in any instance shall not be deemed or construed to be a waiver of such term or condition for the future, or of any subsequent breach thereof. All remedies, rights, undertakings, obligations and agreements contained in the Terms shall be cumulative, and none of them shall be in limitation of any other remedy, right, undertaking, obligation or agreement of either Party.  
      </p>
      <p className="pl-5 text-justify mt-5">
        14.6 <span className="font-semibold">Relationship of Parties:</span> 
        The Parties are not employees, agents, partners or joint venturers of each other. You shall not have the right to enter into any agreement on behalf of the Company. 
      </p>
      <p className="pl-5 text-justify mt-5">
        14.7 <span className="font-semibold">Entire Terms:</span> 
        The entire understanding between the Parties hereto relating to the subject matter hereof is contained herein and the Parties make no warranties, representations or undertakings hereto except as expressly provided herein.  
      </p>
      <p className="pl-5 text-justify mt-5">
        14.8 <span className="font-semibold">Assignment:</span> 
        Notwithstanding anything contained herein, you agree and covenant that the Company may, at its sole discretion, be entitled to assign its rights and obligations under this Terms to any of its affiliates or to any entity, and in such case, such affiliate or entity shall be entitled to enforce these Terms.
      </p>
      <p className="pl-5 text-justify mt-5">
        14.9 <span className="font-semibold">Survival:</span>
        Notwithstanding any termination, cancellation or expiration of the Terms, the provisions hereof that are intended to continue and survive, shall continue and survive. 
      </p>
      <p className="pl-5 text-justify mt-5">
        14.10 <span className="font-semibold">Expenses:</span> 
        Except as otherwise specified in the Terms, all costs and expenses, including fees and disbursements of counsel, financial advisors and accountants, incurred in connection with the Terms and the transactions contemplated in the Terms shall be paid by the Party incurring such costs and expenses. 
      </p>
      <p className="pl-5 text-justify mt-5">
        14.11 <span className="font-semibold">Force Majeure:</span>
        Neither Party shall be liable for a failure or delay in performing any of its obligations under the Terms if, but only to the extent that, such failure or delay is due to causes beyond the reasonable control of the affected party, including, but not limited to
      </p>

      <ol className="list-[lower-roman] pl-10  text-justify">

      <li> acts of God;</li>
      <li> fire or explosion (except to the extent caused by the negligence or willful misconduct of the affected party);</li>
      <li> unusually severe weather;</li>
      <li>war, invasion, riot, or other civil unrest; </li> 
      <li> governmental laws, orders, restrictions, actions, embargoes, or blockages; </li>
      <li> national or regional emergency; and</li>
      <li> injunctions, strikes, lockouts, labor trouble, or other industrial disturbances; provided that the party affected shall promptly notify the other of the force majeure condition and shall exert reasonable efforts to eliminate, cure, or overcome any such causes and to resume performance of its obligations as soon as practicable. </li> 
        </ol>
      <p className="pl-5 text-justify mt-5">
        14.12 <span className="font-semibold">Maintenance of Records:</span>
        You acknowledge and agree that Company shall have the right to retain your information for as long as it deems fit and to be in compliance with applicable provisions of the law. 
      </p>
      <p className="pl-5 text-justify mt-5">
        14.13 <span className="font-semibold">Fees:</span> 
        The Company reserves the right to charge fee for the Services and non-payment may result in denial of Services.
      </p>
      <p className="pl-5 text-justify mt-5">
        14.14 <span className="font-semibold">Notice:</span> 
        Any notices, requests, or communications required or permitted under these Terms shall be in writing and shall be deemed duly given when delivered in person, sent by registered post, courier, or email to the following address: 
        <br></br>
        Company name:<strong> APT Global Fincon Private Limited</strong> <br></br>
      Corporate Office:  <strong>Flat 301, Kamla Hub, N S Road No. 1, Near Criti Care Hospital, Next to Aromas Café, JVPD Scheme, Juhu, Vile Parle West, Mumbai – 400049, INDIA </strong>
       <br></br>
        <strong>Email:</strong> <span className="font-normal text-blue-500">
            <a href="mailto:aptglobalfin@gmail.com">aptglobalfin@gmail.com</a>
          </span>
      </p>
  
      {/* <p className="pl-5">
        14.15 <span className="font-semibold">Modifications:</span> The Company
        may amend or modify these Terms at any time without notice. The Terms
        and conditions as modified shall be effective upon being posted on the
        Platform, and your continued use of the Services shall constitute your
        agreement to such modified Terms.
      </p>
      <p className="pl-5">
        14.16 <span className="font-semibold">Data Protection:</span> You agree
        that your use of the Services may involve the collection, processing,
        and sharing of personal data. The Company will handle such data in
        accordance with its Privacy Policy and applicable laws.
      </p> */}
      <h3 className="font-semibold text-xl mt-4">
         15. General terms for making online payments
      </h3>
      <p className="pl-5 text-justify mt-5">
        15.1 To use the services of the online payment gateway/ payment aggregator service provider, the User shall disclose the exact business category and/or the business sub-category for which it will be using the payment gateway/payment aggregator services. If the User uses the payment gateway/payment aggregator services for any other purpose, the User understands and acknowledges that it shall notify the payment gateway/ payment aggregator service provider and the Company in writing of such change and such change shall be subject to the approval of the payment gateway/ payment aggregator service provider who may include other terms and conditions as it may deem fit. 
      </p>
      <p className="pl-5 text-justify mt-5">
        15.2  In the event You are using any of the Services on the Platform, you agree to provide the Company, as and when necessary, the KYC Documents and other documents requested, including Aadhar card, shops and establishments certificate, utility bills, registrations with tax authorities, memorandum of association, certificate of incorporation, PAN, partnership deed, powers of attorney, etc., and/or any other documents as required under the guidelines, rules and/or regulations issued by the Reserve Bank of India, National Payments Corporation of India, and any other regulatory authorities set up under any applicable laws (“<strong>Regulatory Authorities</strong>”). The User also expressly consents to the Company forwarding the such documents to the payment gateway/ payment aggregator service provider or Regulatory Authorities. 
      </p>
      <p className="pl-5 text-justify mt-5">
        15.3 The User shall indemnify the Company against any losses, damages, or liabilities arising from fraudulent, illegal, or unauthorized payment transactions, including any violations of applicable laws, tax regulations, or financial compliance requirements. The User agrees not to engage in activities that involve unauthorized transactions, misrepresentation, or the submission of false or misleading information through the platform.  
      </p>
      <p className="pl-5 text-justify mt-5">
        15.4 The User acknowledges the Company and the payment gateway/ payment aggregator service provider reserves the right to limit or restrict any transaction size, amount and/or monthly volume at any time. For the purpose of clarity, such limitations or restrictions may be imposed for the following reasons including but not limited to limits/restrictions on the number of purchases which may be charged on the User’s account during any time period, rejection of payment in respect transactions with a prior history of questionable charges, unusual monetary value of transaction, etc. Further, as a security measure, the Company and/ or the payment gateway/ payment aggregator service provider may at its sole discretion block any account numbers or transactions from any specific blocked or blacklisted accounts, group of internet protocol addresses, devices, geographic locations and / or any such risk mitigation measures it wishes to undertake. 
      </p>
      <p className="pl-5 text-justify mt-5">
        15.5 The User hereby agrees and acknowledges that the User shall be solely responsible and liable to pay all relevant taxes pursuant to usage of the payment gateway/ payment aggregator services. 
      </p>
      <p className="pl-5 mt-5">
        15.6 Notwithstanding anything contained in these Terms, the User hereby irrevocably and unconditionally confirms and agree that that the payment gateway/ payment aggregator service provider and Regulatory Authorities reserve the right to reject payments with respect to any transaction for reasons including but not limited to unlawful, unenforceable, doubtful or erroneous transactions, chargebacks, refund, fraud, suspicious activities, authentication and authorization issues, overpayment made due to mathematical errors or otherwise, penalties incurred, transaction related issues, issues in relation to where the transactions were not made in accordance with the requirements of payment gateway/ payment aggregator service provider and/ or the Regulatory Authorities.  
      </p>
      <p className="pl-5 mt-5">
        15.7 The User agrees to comply with all applicable rules, guidelines, instructions, requests and actions, etc. made by the payment gateway/payment aggregator service provider and/or the Regulatory Authorities. The User further acknowledges that the payment gateway/payment aggregator service provider and/or the Regulatory Authorities may also put limitations and restrictions on the User, at its sole discretion from time to time. In addition, the payment gateway/ payment aggregator service provider and the Company has the right to reverse/reject payments, suspend and/or terminate services, make inspections or inquiries in relation to the transaction, etc. In the event any fines, penalties or other amounts are levied by the payment gateway/ payment aggregator service provider and/or the Regulatory Authorities on the Company, then without prejudice to Company’s other rights under law, the User shall forthwith reimburse the Company an amount equal to the fines, penalties or other amount so levied or demanded.  
      </p>
      <p className="pl-5 mt-5">
        15.8 The User agrees and expressly consents to provide the Company any documentary evidence as may be required in relation to any disputes relating to rejection/ termination of transactions included any explanatory statements is support of such disputes 
      </p>
      <p className="pl-5 mt-5">15.9 The User expressly consents and agrees to </p>
     
     <ol className="list-[lower-roman] list-inside pl-10 text-justify">
     <li> the Company maintaining records in relation to the User’s transactions; and</li> 
     <li>maintaining records by itself  in relation to the User’s transactions, for the purposes of inspection by the payment gateway/ payment aggregator service provider, and/or the Regulatory Authorities  </li>
     </ol>

      <p className="pl-5 mt-5">
        15.10 The User agrees to indemnify the Company in respect of any claims, disputes, penalties, costs and expenses arising directly or indirectly in relation to refunds or chargebacks for all payment transactions initiated by the User on the Platform. In event of rejection of any payment by any payment gateway/ payment aggregator service provider and/or Regulatory Authorities and the Company shall be not responsible to collect the payment from such payment gateway/ payment aggregator service provider or bank directly and in any case shall also not have any responsibility or liability in this regard.  
      </p>
      <p className="pl-5 mt-5">
        15.11 The Users agree to comply with all Know Your Customer (KYC), anti-money laundering (AML), anti-bribery, and anti-corruption laws as applicable under Indian law and as may be prescribed by relevant Regulatory Authorities including the Reserve Bank of India (RBI), Securities and Exchange Board of India (SEBI), and other competent authorities. The Company reserves the right to suspend or terminate services in case of non-compliance. 
      </p>
      <h3 className="font-semibold text-xl mt-4">16. Privacy Policy</h3>
      <p className="pl-5 text-justify mt-5">
        We value your privacy and are committed to protecting your personal
        data. The collection, use, storage, and disclosure of personal
        information provided by users while using ezyfiling are governed by our
         <strong> Privacy Policy</strong>, which is maintained as a separate document.
        <br />
        By using our platform, you acknowledge and agree that your data will be
        handled in accordance with our <strong>Privacy Policy</strong>, which outlines:
      </p>
      <div className="mt-4">
        <p className="pl-5">I. The types of information we collect.</p>
        <p className="pl-5">II. How we use and store your data.</p>
        <p className="pl-5">
          III. Your rights regarding your personal information.
        </p>
        <p className="pl-5">
          IV. Security measures implemented to protect user data.
        </p>
        <p className="pl-5">
          V. Conditions under which data may be shared with third parties.
        </p>
      </div>
      <p className="mt-5">
        For detailed information on how we handle your personal data, please
        refer to our <strong>Privacy Policy</strong>, available at our website:{" "}
        <a href="https://www.ezyfiling.com"><strong>www.ezyfiling.com</strong> </a>
      </p>
    </div>
  );
};

export default TermsAndConditions;
